spring.application.name=safewallet

# 1. CONEXÃO DO DATASOURCE (Dinâmico para nuvem, mantendo fallback local na porta padrão 5432)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/db_safewallet}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. DIALETO E COMPORTAMENTO DO ORM HIBERNATE
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

api.security.token.secret=${JWT_SECRET:minha-chave-secreta-e-super-protegida-safewallet-core-2026}