# ========================================================================
# CONFIGURAÇÕES DE DIRETRIZES DE REDE - SAFEWALLET CORE
# ========================================================================
spring.application.name=safewallet

# 1. CONEXÃO DO DATASOURCE (Mapeado estritamente para a porta isolada 5433)
spring.datasource.url=jdbc:postgresql://localhost:5433/db_safewallet
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. DIALETO E COMPORTAMENTO DO ORM HIBERNATE
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Desativa o aviso chato de consultas abertas na camada de visualização
spring.jpa.open-in-view=false

# Configuração do Perímetro de Segurança da SafeWallet
api.security.token.secret=minha-chave-secreta-e-super-protegida-safewallet-core-2026